### ISSUE TITLE
Inverting polarity in headless setup without

### ISSUE THREAD

**Issue by guussie** [moode-player/protodac#1]
I use ProtoDAC on a headless Raspberry Pi.

How can I invert the polarity of the audio output manually through configuration files?

**Comment by moodeaudio** [comment]
Questions and troubleshooting are handled in the Support section of our Forum so that all our users can benefit from the discussion.

Email forum at moodeaudio dot org and let me know what userid you would like to use (at least 5 characters) and an account will be created for you.
