### ISSUE TITLE
Gerber file revision 2E missing ground to RCA output

### ISSUE THREAD

**Issue by pierretu** [moode-player/protodac#2]
Im just letting you know that your gerber file revision 2E is missing ground on the RCA output.
Or atleast missing from my order made from JLCPCB using the 2E gerber file.

**Comment by hifisys** [comment]
I think the PCB you received is a manufacturing defect. 

If you load the Gerber zip file into the JLCPCB website and look at the Gerber view, there are clearly connections from the RCA ground leads to the ground plane.

I spot checked the PCBs I received from JLCPCB, and they are correct. I have shipped nearly 50 PCBs of version 2E, and no one has reported a problem.

Note that the two large posts on the RCA jack are mechanical supports only, and have no internal electrical connection. Those associated PCB pads are not connected to the ground plane.

**Comment by pierretu** [comment]
It could be faulty cards if you got them working with the 2E.

I have soldered a simple jumper cable to the ground plane and have working cards. Took a little measuring to figure out what was wrong.

Closing issue
